server:
  port: 8101
spring:
  session:
    # 存储类型修改为redis
    store-type: redis
    redis:
      # Redis服务器的信息，该咋写咋写
      host: 127.0.0.1
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858